package edu.stanford.bmir.protege.web.server.app;

import java.util.regex.Pattern;

/**
 * Matthew Horridge
 * Stanford Center for Biomedical Informatics Research
 * 04/01/15
 */
public class GwtResourceCachingStrategy implements ResourceCachingStrategy {

    /**
     * Matches resources generated by the GWT compiler that should be cached.
     */
    private static final Pattern CACHE_PATTERN = Pattern.compile(".+\\.cache\\..+");

    @Override
    public boolean shouldCacheResource(String requestURI) {
        return CACHE_PATTERN.matcher(requestURI).matches();
    }
}
